### PR TITLE
feat: return svg string

### PR DESCRIPTION
**Pull request by amanzrx4**
Hey @YYsuni Thanks for the library. For our usecase we just want an svg string. Can you consider adding this change? Thanks

### CODE REVIEW

**Comment by YYsuni** [comment]
I believe this parameter has the potential to affect other users. It would be more appropriate to create a new function to separate the SVG raw string.

**Comment by amanzrx4** [comment]
agree @YYsuni 
I've abstracted into a seperate function, let me know if it works

**Comment by YYsuni** [comment]
Thanks for using, I will update the project for a better dev experience and usage.

**Comment by amanzrx4** [comment]
thankyou

**Pull request merged**
